export const privatePolicy = `<p><span style="font-weight: 400;">Polityka prywatności i ochrona danych osobowych.</span></p>
<p><span style="font-weight: 400;">Zagadnienia wstępne</span></p>
<p><span style="font-weight: 400;">Niniejsza Polityka Prywatności obowiązuje od dnia 01 września 2025 r. a jej postanowienia dostosowane zostały do wymog&oacute;w Rozporządzenia Parlamentu Europejskiego I Rady (UE) 2016/672 z dnia 27 kwietnia 2016 r. w sprawie ochrony os&oacute;b fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych oraz uchylenia dyrektywy 95/46/WE oraz ustawy z dnia 10 maja 2018 r. o ochronie danych osobowych.</span></p>
<p><span style="font-weight: 400;">Celem wdrożenia niniejszej Polityki Prywatności jest zapewnienie naszym Użytkownikom pełnego poszanowania ich prywatności oraz ochrony ich danych osobowych podczas korzystania z usług naszego Sklepu.</span></p>
<p><span style="font-weight: 400;">Słowniczek</span></p>
<p><span style="font-weight: 400;">Na potrzeby niniejszego dokumentu:</span></p>
<p><span style="font-weight: 400;">&bdquo;Administratorem Danych Osobowych&rdquo; jest sp&oacute;łka Deccore sp. z o.o., Grzybowska 4 / 96, 00-131 Warszawa; KRS 0001083010, REGON 527536161, NIP 5252989674 (zwany dalej r&oacute;wnież &bdquo;Administratorem&rdquo; lub &bdquo;Sklepem&rdquo;);</span></p>
<p><span style="font-weight: 400;">&bdquo;dane osobowe&rdquo; oznaczają informacje o zidentyfikowanej lub możliwej do zidentyfikowania osobie fizycznej ("osobie, kt&oacute;rej dane dotyczą"); możliwa do zidentyfikowania osoba fizyczna to osoba, kt&oacute;rą można bezpośrednio lub pośrednio zidentyfikować, w szczeg&oacute;lności na podstawie identyfikatora takiego jak np. imię i nazwisko, numer identyfikacyjny, dane o lokalizacji, identyfikator internetowy lub jeden bądź kilka szczeg&oacute;lnych czynnik&oacute;w określających fizyczną, fizjologiczną, genetyczną, psychiczną, ekonomiczną, kulturową lub społeczną tożsamość osoby fizycznej;</span></p>
<p><span style="font-weight: 400;">&nbsp;&bdquo;naruszenie ochrony danych osobowych&rdquo; oznacza naruszenie bezpieczeństwa prowadzące do przypadkowego lub niezgodnego z prawem zniszczenia, utracenia, zmodyfikowania, nieuprawnionego ujawnienia lub nieuprawnionego dostępu do danych osobowych przesyłanych, przechowywanych lub w inny spos&oacute;b przetwarzanych;</span></p>
<p><span style="font-weight: 400;">&bdquo;newsletter&rdquo; oznacza elektroniczną formę biuletynu, służącą do informowania Użytkownik&oacute;w sklepu m.in. o akcjach promocyjnych oraz nowościach w sklepie www.nextdesignsummit.pl;</span></p>
<p><span style="font-weight: 400;">&bdquo;odbiorca&rdquo; oznacza osobę fizyczną lub prawną, organ publiczny, jednostkę lub inny podmiot, kt&oacute;remu ujawnia się dane osobowe, niezależnie od tego, czy jest stroną trzecią. Organy publiczne, kt&oacute;re mogą otrzymywać dane osobowe w ramach konkretnego postępowania zgodnie z prawem Unii lub prawem państwa członkowskiego, nie są jednak uznawane za odbiorc&oacute;w; przetwarzanie tych danych przez te organy publiczne musi być zgodne z przepisami o ochronie danych mającymi zastosowanie stosownie do cel&oacute;w przetwarzania;</span></p>
<p><span style="font-weight: 400;">&bdquo;ograniczenie przetwarzania&rdquo; oznacza oznaczenie przechowywanych danych osobowych w celu ograniczenia ich przyszłego przetwarzania;</span></p>
<p><span style="font-weight: 400;">&bdquo;organ nadzorczy&rdquo; oznacza niezależny organ publiczny ustanowiony przez państwo członkowskie zgodnie z art. 51 Rozporządzenia, kt&oacute;rym jest Prezes Urzędu Ochrony Danych Osobowych: ul. Stawki 2, 00-193 Warszawa;</span></p>
<p><span style="font-weight: 400;">&bdquo;podmiot przetwarzający&rdquo; oznacza osobę fizyczną lub prawną, organ publiczny, jednostkę lub inny podmiot, kt&oacute;ry przetwarza dane osobowe w imieniu administratora;</span></p>
<p><span style="font-weight: 400;">&bdquo;poufność danych&rdquo; oznacza właściwość zapewniająca, że dane nie są udostępniane nieupoważnionym podmiotom;</span></p>
<p><span style="font-weight: 400;">&bdquo;przetwarzanie&rdquo; oznacza operację lub zestaw operacji wykonywanych na danych osobowych lub zestawach danych osobowych w spos&oacute;b zautomatyzowany lub niezautomatyzowany, taką jak zbieranie, utrwalanie, organizowanie, porządkowanie, przechowywanie, adaptowanie lub modyfikowanie, pobieranie, przeglądanie, wykorzystywanie, ujawnianie poprzez przesłanie, rozpowszechnianie lub innego rodzaju udostępnianie, dopasowywanie lub łączenie, ograniczanie, usuwanie lub niszczenie;</span></p>
<p><span style="font-weight: 400;">&nbsp;&bdquo;Rozporządzenie&rdquo; oznacza Rozporządzenie Parlamentu Europejskiego i Rady (UE) 2016/679 z 27 kwietnia 2016 r. w sprawie ochrony os&oacute;b fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych oraz uchylenia dyrektywy 95/46/WE (dalej: &bdquo;RODO&rdquo;);</span></p>
<p><span style="font-weight: 400;">&bdquo;ustawa&rdquo; &ndash; oznacza ustawę z dnia 10 maja 2018 r. o ochronie danych osobowych;</span></p>
<p><span style="font-weight: 400;">&nbsp;&bdquo;usuwanie danych&rdquo; oznacza zniszczenie danych osobowych lub taką ich modyfikację, kt&oacute;ra nie pozwala na ustalenie tożsamości osoby, kt&oacute;rej dane dotyczą (&rdquo;anonimizacja&rdquo;),</span></p>
<p><span style="font-weight: 400;">&bdquo;uwierzytelnienie&rdquo; oznacza działanie, kt&oacute;rego celem jest weryfikacja deklarowanej tożsamości podmiotu;</span></p>
<p><span style="font-weight: 400;">&bdquo;Użytkownik</span><span style="font-weight: 400;">&rdquo; oznacza osobę fizyczną, posiadająca pełną lub ograniczoną zdolność do czynności prawnych, osobę prawną lub jednostkę organizacyjną posiadającą osobowość prawną dokonującą w Sklepie zakupu jako gość;</span></p>
<p><span style="font-weight: 400;">&bdquo;zgoda osoby, kt&oacute;rej dane dotyczą&rdquo; oznacza dobrowolne, konkretne, świadome i jednoznaczne okazanie woli, kt&oacute;rym osoba, kt&oacute;rej dane dotyczą, w formie oświadczenia lub wyraźnego działania potwierdzającego, przyzwala na przetwarzanie dotyczących jej danych osobowych.</span></p>
<p><span style="font-weight: 400;">Administrator Danych Osobowych. Cele, zakres i podstawy przetwarzania</span></p>
<p><span style="font-weight: 400;">Administratorem Danych Osobowych Użytkownik&oacute;w sklepu internetowego www.nextdesignsummit.pl jest sp&oacute;łka sp&oacute;łka Deccore sp. z o.o., Grzybowska 4 / 96, 00-131 Warszawa; KRS 0001083010, REGON 527536161, NIP 5252989674.</span></p>
<p><span style="font-weight: 400;">Kontakt ze Sklepem w każdej sprawie związanej z ochroną danych osobowych Użytkownika możliwy jest za pośrednictwem poczty elektronicznej pod adresem: biuro@nextdesignsummit.pl,</span></p>
<p><span style="font-weight: 400;">Dane osobowe Użytkownika przetwarzane są wyłącznie w celach:</span></p>
<p><span style="font-weight: 400;">zarejestrowania i utrzymywania konta Użytkownika, kt&oacute;re służy Użytkownikom do dokonywania zakup&oacute;w w sklepie internetowym nextdesignsummit.pl;</span></p>
<p><span style="font-weight: 400;">kontaktu pomiędzy Użytkownikiem a Administratorem Danych Osobowych, we wszystkich sprawach związanych ze złożonym zam&oacute;wieniem; realizacji zwartych z Administratorem Danych Osobowych um&oacute;w sprzedaży;</span></p>
<p><span style="font-weight: 400;">realizacji zgłoszonych Administratorowi Danych Osobowych reklamacji;</span></p>
<p><span style="font-weight: 400;">przesyłania informacji handlowych i marketingowych;</span></p>
<p><span style="font-weight: 400;">rachunkowych i podatkowych, wynikających z ciążących na Administratorze Danych Osobowych obowiązkach prawnych;</span></p>
<p><span style="font-weight: 400;">ustalenia, dochodzenia lub obrony roszczeń Administratora Danych Osobowych, w tym w celach windykacyjnych i do prowadzenia postępowań sądowych;</span></p>
<p><span style="font-weight: 400;">Użytkownik podaje swoje dane dobrowolnie udzielając Administratorowi Danych Osobowych zgody na ich przetwarzanie w celach opisanych w ustępie poprzedzającym. Nieudzielenie przez Użytkownika zgody na przetwarzanie danych osobowych skutkuje odmową założenia konta Użytkownika oraz uniemożliwi kontakt za pośrednictwem formularza kontaktowego.</span></p>
<p><span style="font-weight: 400;">Podstawą przetwarzania danych osobowych Użytkownik&oacute;w, kierujących za pośrednictwem formularza kontaktowego zapytania ofertowe oraz zapisanych do newslettera, jest uzyskanie dobrowolnej zgody na przesyłanie informacji marketingowych i handlowych, zgodnie z przepisami ustawy z dnia 18 lipca 2002 roku o świadczenie usług drogą elektroniczną oraz ustawy z dnia 16 lipca 2004 roku &ndash; prawo telekomunikacyjne. Wyrażenie przez Użytkownika zgody na otrzymywanie informacji handlowych i marketingowych jest wymagane celem przesłania mu szczeg&oacute;łowych informacji dotyczących oferty Administratora Danych Osobowych.</span></p>
<p><span style="font-weight: 400;">Podstawą przetwarzania danych osobowych Użytkownik&oacute;w podczas składania zam&oacute;wienia w sklepie internetowym nextdesignsummit.pl jest art. 6 ust 1 lit b Rozporządzenia &ndash; zawarcie umowy.</span></p>
<p><span style="font-weight: 400;">Administrator Danych Osobowych przetwarza następujące dane osobowe Użytkownika:</span></p>
<ol>
<li><span style="font-weight: 400;">a) w przypadku składania zam&oacute;wienia w Sklepie, Użytkownik podaje następujące dane: imię i nazwisko, adres e-mail, telefon kontaktowy, dane adresowe (kod pocztowy, miejscowość, nazwa ulicy, numer domu/mieszkania);</span></li>
<li><span style="font-weight: 400;">b) w przypadku skorzystania z usługi Newsletter Użytkownik podaje: adres e-mail.</span></li>
</ol>`;

export const terms = `<p><span style="font-weight: 400;">Niniejszy Regulamin określa og&oacute;lne warunki, zasady oraz spos&oacute;b sprzedaży prowadzonej przez </span><span style="font-weight: 400;">Deccore sp. z o.o. z</span><span style="font-weight: 400;"> siedzibą w Warszawie, za pośrednictwem sklepu internetowego www.nextdesignsummit.pl (zwanego dalej: &bdquo;Sklepem Internetowym&rdquo;) oraz określa zasady i warunki świadczenia przez Deccore sp z.o.o z siedzibą w Warszawie usług nieodpłatnych drogą elektroniczną.</span></p>
<p>&nbsp;</p>
<p><strong>1 Definicje</strong></p>
<ol>
<li><span style="font-weight: 400;"> Dni robocze - oznacza dni tygodnia od poniedziałku do piątku z wyłączeniem dni ustawowo wolnych od pracy.</span></li>
<li><span style="font-weight: 400;"> Klient - oznacza podmiot, na rzecz kt&oacute;rego zgodnie z Regulaminem i przepisami prawa mogą być świadczone usługi drogą elektroniczną lub z kt&oacute;rym zawarta może być Umowa sprzedaży.</span></li>
<li><span style="font-weight: 400;"> Konsument - oznacza osobę fizyczną dokonującą z przedsiębiorcą czynności prawnej niezwiązanej bezpośrednio z jej działalnością gospodarczą lub zawodową.</span></li>
<li><span style="font-weight: 400;"> Przedsiębiorca - oznacza osobę fizyczną, osobę prawną lub jednostkę organizacyjną niebędącą osobą prawną, kt&oacute;rej ustawa przyznaje zdolność prawną, prowadzącą we własnym imieniu działalność gospodarczą lub zawodową i dokonującą czynności prawnej związaną bezpośrednio z jej działalnością gospodarczą lub zawodową.</span></li>
<li><span style="font-weight: 400;"> Regulamin - oznacza niniejszy regulamin.</span></li>
<li><span style="font-weight: 400;"> Rejestracja - oznacza czynność faktyczną dokonaną w spos&oacute;b określony w Regulaminie, wymaganą dla korzystania przez Klienta ze wszystkich funkcjonalności Sklepu Internetowego.</span></li>
<li><span style="font-weight: 400;"> Sprzedawca - oznacza:</span></li>
</ol>
<p><span style="font-weight: 400;">Deccore sp. z o.o., Grzybowska 4 / 96, 00-131 Warszawa; KRS 0001083010, REGON 527536161, NIP 5252989674, email: biuro@nextdesignsummit.pl, będącej jednocześnie właścicielem Sklepu Internetowego. Nr konta bankowego: Jest Bank nr: 06 1160 2202 0000 0006 0161 6133</span></p>
<ol start="8">
<li><span style="font-weight: 400;"> Strona Internetowa Sklepu - oznacza strony internetowe, pod kt&oacute;rymi Sprzedawca prowadzi Sklep Internetowy, działające w domenie www.nextdesignsummit.pl</span></li>
<li><span style="font-weight: 400;"> Towar - oznacza produkt przedstawiony przez Sprzedawcę za pośrednictwem Strony Internetowej Sklepu, mogący być przedmiotem Umowy sprzedaży.</span></li>
<li><span style="font-weight: 400;"> Trwały nośnik - oznacza materiał lub narzędzie umożliwiające Klientowi lub Sprzedawcy przechowywanie informacji kierowanych osobiście do niego, w spos&oacute;b umożliwiający dostęp do informacji w przyszłości przez czas odpowiedni do cel&oacute;w, jakim te informacje służą, i kt&oacute;re pozwalają na odtworzenie przechowywanych informacji w niezmienionej postaci.</span></li>
<li><span style="font-weight: 400;"> Umowa sprzedaży - oznacza umowę sprzedaży zawartą na odległość, na zasadach określonych w Regulaminie, między Klientem a Sprzedawcą.</span></li>
</ol>
<p>&nbsp;</p>
<p><strong>2 Postanowienia og&oacute;lne i korzystanie ze Sklepu Internetowego</strong></p>
<ol>
<li><span style="font-weight: 400;"> Wszelkie prawa do Sklepu Internetowego, w tym majątkowe prawa autorskie, prawa własności intelektualnej do jego nazwy, jego domeny internetowej, Strony Internetowej Sklepu, a także do wzorc&oacute;w, formularzy, logotyp&oacute;w zamieszczanych na Stronie Internetowej Sklepu (za wyjątkiem logotyp&oacute;w i zdjęć prezentowanych na Stronie Internetowej Sklepu w celach prezentacji towar&oacute;w, do kt&oacute;rych to prawa autorskie należą do podmiot&oacute;w trzecich) należą do Sprzedawcy, a korzystanie z nich może następować wyłącznie w spos&oacute;b określony i zgodny z Regulaminem oraz za zgodą Sprzedawcy wyrażoną na piśmie.</span></li>
<li><span style="font-weight: 400;"> Sprzedawca dołoży starań, aby korzystanie ze Sklepu Internetowego było możliwe dla użytkownik&oacute;w Internetu z użyciem wszystkich popularnych przeglądarek internetowych, system&oacute;w operacyjnych, typ&oacute;w urządzeń oraz typ&oacute;w połączeń internetowych. Minimalne wymagania techniczne umożliwiające korzystanie ze Strony Internetowej Sklepu to przeglądarka internetowa w wersji co najmniej Chrome 39 lub FireFox 34 lub Opera 26 lub Safari 5 lub nowszych, z włączoną obsługą języka Javascript, akceptująca pliki typu &bdquo;cookies&rdquo; oraz łącze internetowe o przepustowości co najmniej 256 kbit/s. Strona Internetowa Sklepu jest zoptymalizowana dla minimalnej rozdzielczości ekranu 1024x768 pikseli.</span></li>
<li><span style="font-weight: 400;"> Sprzedawca stosuje mechanizm plik&oacute;w "cookies", kt&oacute;re podczas korzystania przez Klient&oacute;w ze Strony Internetowej Sklepu, zapisywane są przez serwer Sprzedawcy na dysku twardym urządzenia końcowego Klienta. Stosowanie plik&oacute;w "cookies" ma na celu poprawne działanie Strony Internetowej Sklepu na urządzeniach końcowych Klient&oacute;w. Mechanizm ten nie niszczy urządzenia końcowego Klienta oraz nie powoduje zmian konfiguracyjnych w urządzeniach końcowych Klient&oacute;w ani w oprogramowaniu zainstalowanym na tych urządzeniach. Każdy Klient może wyłączyć mechanizm &bdquo;cookies&rdquo; w przeglądarce internetowej swojego urządzenia końcowego. Sprzedawca wskazuje, że wyłączenie &bdquo;cookies&rdquo; może jednak spowodować utrudnienia lub uniemożliwić korzystanie ze Strony Internetowej Sklepu.</span></li>
<li><span style="font-weight: 400;"> W celu złożenia zam&oacute;wienia w Sklepie Internetowym za pośrednictwem Strony Internetowej Sklepu oraz w celu korzystania z usług świadczonych drogą elektroniczną za pośrednictwem Strony Internetowej Sklepu, konieczne jest posiadanie przez Klienta aktywnego konta poczty elektronicznej.</span></li>
<li><span style="font-weight: 400;"> Zakazane jest dostarczanie przez Klienta treści o charakterze bezprawnym oraz wykorzystywanie przez Klienta Sklepu Internetowego, Strony Internetowej Sklepu lub usług nieodpłatnych świadczonych przez Sprzedawcę, w spos&oacute;b sprzeczny z prawem, dobrymi obyczajami lub naruszający dobra osobiste os&oacute;b trzecich.</span></li>
<li><span style="font-weight: 400;"> Sprzedawca oświadcza, iż publiczny charakter sieci Internet i korzystanie z usług świadczonych drogą elektroniczną wiązać może się z zagrożeniem pozyskania i modyfikowania danych Klient&oacute;w przez osoby nieuprawnione, dlatego Klienci powinni stosować właściwe środki techniczne, kt&oacute;re zminimalizują wskazane wyżej zagrożenia. W szczeg&oacute;lności powinni stosować programy antywirusowe i chroniące tożsamość korzystających z sieci Internet. Sprzedawca nigdy nie zwraca się do Klienta z prośbą o udostępnienie mu w jakiejkolwiek formie Hasła.</span></li>
<li><span style="font-weight: 400;"> Nie jest dopuszczalne wykorzystywanie zasob&oacute;w i funkcji Sklepu Internetowego w celu prowadzenia przez Klienta działalności, kt&oacute;ra naruszałaby interes Sprzedawcy.</span></li>
</ol>
<p>&nbsp;</p>
<p><strong>3 Zam&oacute;wienia</strong></p>
<ol>
<li><span style="font-weight: 400;"> Informacje zawarte na Stronie Internetowej Sklepu nie stanowią oferty Sprzedawcy w rozumieniu Kodeksu cywilnego, a jedynie zaproszenie Klient&oacute;w do składania ofert zawarcia Umowy sprzedaży.</span></li>
<li><span style="font-weight: 400;"> Klient może składać zam&oacute;wienia w Sklepie Internetowym za pośrednictwem Strony Internetowej Sklepu przez 7 dni w tygodniu, 24 godziny na dobę.</span></li>
<li><span style="font-weight: 400;"> Klient składający zam&oacute;wienie za pośrednictwem Strony Internetowej Sklepu, kompletuje zam&oacute;wienie wybierając Towar, kt&oacute;rym jest zainteresowany. Dodanie Towaru do zam&oacute;wienia następuje przez wyb&oacute;r polecenia Kup Bilet prezentowanym na Stronie Internetowej Sklepu. Klient po skompletowaniu całości zam&oacute;wienia i wskazaniu formy płatności, składa zam&oacute;wienie przez wysłanie formularza zam&oacute;wienia do Sprzedawcy, wybierając na Stronie Internetowej Sklepu przycisk &bdquo;Zamawiam i płacę&rdquo;. Każdorazowo przed wysyłką zam&oacute;wienia do Sprzedawcy, Klient jest informowany o łącznej cenie za wybrany Towar, jak też o wszystkich dodatkowych kosztach jakie jest zobowiązany ponieść w związku z Umową sprzedaży.</span></li>
<li><span style="font-weight: 400;"> Złożenie zam&oacute;wienia stanowi złożenie Sprzedawcy przez Klienta oferty zawarcia Umowy sprzedaży Towar&oacute;w będących przedmiotem zam&oacute;wienia.</span></li>
<li><span style="font-weight: 400;"> Po złożeniu zam&oacute;wienia, Sprzedawca przesyła na podany przez Klienta adres poczty elektronicznej potwierdzenie jego złożenia.</span></li>
<li><span style="font-weight: 400;"> Następnie, po potwierdzeniu złożenia zam&oacute;wienia, Sprzedawca przesyła na podany przez Klienta adres poczty elektronicznej informację o przyjęciu zam&oacute;wienia do realizacji. Informacja o przyjęciu zam&oacute;wienia do realizacji jest oświadczeniem Sprzedawcy o przyjęciu oferty, o kt&oacute;rej mowa w &sect;4 ust. 7 powyżej i z chwilą jego otrzymania przez Klienta zostaje zawarta Umowa sprzedaży.</span></li>
<li><span style="font-weight: 400;"> Po zawarciu Umowy sprzedaży, Sprzedawca potwierdza Klientowi jej warunki, przesyłając je na Trwałym nośniku na adres poczty elektronicznej Klienta lub pisemnie na wskazany przez Klienta podczas Rejestracji lub składania zam&oacute;wienia adres.</span></li>
</ol>
<p>&nbsp;</p>
<p><strong>5 Płatności</strong></p>
<ol>
<li><span style="font-weight: 400;"> Ceny na Stronie Internetowej Sklepu zamieszczone przy danym Towarze stanowią ceny brutto i nie zawierają informacji odnośnie koszt&oacute;w Dostawy i wszelkich innych koszt&oacute;w, kt&oacute;re Klient będzie zobowiązany ponieść w związku z Umową sprzedaży, o kt&oacute;rych Klient będzie poinformowany przy wyborze sposobu Dostawy i składaniu zam&oacute;wienia.</span></li>
<li><span style="font-weight: 400;"> Klient może wybrać następujące formy płatności za zam&oacute;wione Towary:</span></li>
<li><span style="font-weight: 400;">a) przelew bankowy na rachunek bankowy Sprzedawcy (w tym przypadku realizacja zam&oacute;wienia rozpoczęta zostanie po przesłaniu Klientowi przez Sprzedawcę potwierdzenia przyjęcia zam&oacute;wienia oraz po wpłynięciu środk&oacute;w na rachunek bankowy Sprzedawcy);</span></li>
<li><span style="font-weight: 400;">b) przelew bankowy oraz płatność kartą poprzez zewnętrzny system płatności PayU, obsługiwany przez firmę PayU S.A. z siedzibą w Poznaniu (w tym przypadku realizacja zam&oacute;wienia rozpoczęta zostanie po przesłaniu Klientowi przez Sprzedawcę potwierdzenia przyjęcia zam&oacute;wienia oraz po otrzymaniu przez Sprzedawcę informacji z systemu PayU o dokonaniu płatności przez Klienta);</span></li>
<li><span style="font-weight: 400;"> Klient jest każdorazowo informowany przez Sprzedawcę na Stronie Internetowej Sklepu o terminie w jakim jest zobowiązany dokonać płatności za zam&oacute;wienie w wysokości wynikającej z zawartej Umowy sprzedaży. W wypadku niewywiązania się przez Klienta z płatności w terminie, o kt&oacute;rym mowa w &sect;5 ust. 3 Regulaminu, Sprzedawca wyznacza Klientowi dodatkowy termin na dokonanie płatności i informuje o nim Klienta na Trwałym nośniku. Informacja o dodatkowym terminie na dokonanie płatności zawiera r&oacute;wnież informację, że po bezskutecznym upływie tego terminu, Sprzedawca odstąpi od Umowy sprzedaży. W wypadku bezskutecznego upływu drugiego terminu na dokonanie płatności, Sprzedawca prześle Klientowi na Trwałym nośniku oświadczenie o odstąpieniu od umowy na podstawie art. 491 Kodeksu Cywilnego.</span></li>
</ol>
<p>&nbsp;</p>
<p><strong>6 Dostawa</strong></p>
<ol>
<li><span style="font-weight: 400;"> Sprzedawca realizuje Dostawę na terytorium Rzeczypospolitej Polskiej.</span></li>
<li><span style="font-weight: 400;"> Sprzedawca jest zobowiązany dostarczyć Towar będący przedmiotem Umowy sprzedaży bez wad.</span></li>
<li><span style="font-weight: 400;"> Sprzedawca zamieszcza na Stronie Internetowej Sklepu informację o liczbie Dni Roboczych potrzebnych do Dostawy i realizacji zam&oacute;wienia.</span></li>
<li><span style="font-weight: 400;"> Termin Dostawy i realizacji zam&oacute;wienia wskazany na Stronie Internetowej Sklepu liczony jest w Dniach roboczych zgodnie z &sect;5 ust. 2 Regulaminu.</span></li>
<li><span style="font-weight: 400;"> Zam&oacute;wione Towary są dostarczane do Klienta za pośrednictwem Dostawcy na adres e-mail wskazany w formularzu zam&oacute;wienia.</span></li>
<li><span style="font-weight: 400;"> W dniu wysłania Towaru do Klienta przekazywana jest na adres poczty elektronicznej Klienta informacja potwierdzająca nadanie przesyłki przez Sprzedawcę.</span></li>
<li><span style="font-weight: 400;"> Klient powinien zbadać doręczoną przesyłkę w czasie i w spos&oacute;b przyjęty przy przesyłkach danego rodzaju, w obecności pracownika Dostawcy. W razie stwierdzenia ubytku lub uszkodzenia przesyłki Klient ma prawo żądać od pracownika Dostawcy spisania właściwego protokołu.</span></li>
<li><span style="font-weight: 400;"> Sprzedawca, zgodnie z wolą Klienta, dołącza do przesyłki będącej przedmiotem Dostawy paragon albo fakturę VAT obejmującą dostarczane Towary.</span></li>
</ol>
<p>&nbsp;</p>
<p><strong>7 Rękojmia</strong></p>
<ol>
<li><span style="font-weight: 400;"> Sprzedawca zapewnia Dostawę Towaru pozbawionego wad fizycznych i prawnych. Sprzedawca jest odpowiedzialny względem Klienta, jeżeli Towar ma wadę fizyczną lub prawną (rękojmia).</span></li>
<li><span style="font-weight: 400;"> Jeżeli Towar ma wadę Klient może:</span></li>
<li><span style="font-weight: 400;">a) złożyć oświadczenie o obniżeniu ceny albo odstąpieniu od Umowy sprzedaży, chyba że Sprzedawca niezwłocznie i bez nadmiernych niedogodności dla Klienta wymieni Towar wadliwy na wolny od wad albo wadę usunie. Ograniczenie to nie ma zastosowania, jeżeli Towar był już wymieniony lub naprawiany przez sprzedawcę albo sprzedawca nie uczynił zadość obowiązkowi wymiany Towaru na wolny od wad lub usunięcia wad. Klient może zamiast zaproponowanego przez Sprzedawcę usunięcia wady żądać wymiany Towaru na wolny od wad albo zamiast wymiany Towaru żądać usunięcia wady, chyba że doprowadzenie rzeczy do zgodności z umową w spos&oacute;b wybrany przez Klienta jest niemożliwe albo wymagałoby nadmiernych koszt&oacute;w w por&oacute;wnaniu ze sposobem proponowanym przez Sprzedawcę. Przy ocenie nadmierności koszt&oacute;w uwzględnia się wartość Towaru wolnego od wad, rodzaj i znaczenie stwierdzonej wady, a także bierze się pod uwagę niedogodności, na jakie narażałby Klienta inny spos&oacute;b zaspokojenia.</span></li>
<li><span style="font-weight: 400;">b) żądać wymiany Towaru wadliwego na wolny od wad albo usunięcia wady. Sprzedawca jest obowiązany wymienić Towar wadliwy na wolny od wad lub usunąć wadę w rozsądnym czasie bez nadmiernych niedogodności dla Klienta.</span></li>
</ol>
<p><span style="font-weight: 400;">&nbsp;Sprzedawca może odm&oacute;wić zadość uczynienia żądaniu Klienta, jeżeli doprowadzenie do zgodności z Umową sprzedaży Towaru wadliwego w spos&oacute;b wybrany przez Klienta jest niemożliwe lub w por&oacute;wnaniu z drugim możliwym sposobem doprowadzenia do zgodności z Umową sprzedaży wymagałoby nadmiernych koszt&oacute;w. Koszty naprawy lub wymiany ponosi Sprzedawca.</span></p>
<ol start="3">
<li><span style="font-weight: 400;"> Klient, kt&oacute;ry wykonuje uprawnienia z tytułu rękojmi, jest obowiązany dostarczyć rzecz wadliwą na adres Sprzedawcy. W wypadku Klienta będącego Konsumentem koszt dostarczenia pokrywa Sprzedawca.</span></li>
<li><span style="font-weight: 400;"> Sprzedawca odpowiada z tytułu rękojmi, jeżeli wada fizyczna zostanie stwierdzona przed upływem dw&oacute;ch lat od wydania Towaru Klientowi. Roszczenie o usunięcie wady lub wymianę Towaru na wolny od wad przedawnia się z upływem roku, lecz termin ten nie może zakończyć się przed upływem terminu określonego w zdaniu pierwszym. W tym terminie Klient może odstąpić od Umowy sprzedaży lub złożyć oświadczenie o obniżeniu ceny z powodu wady Towaru. Jeżeli Klient żądał wymiany Towaru na wolny od wad lub usunięcia wady, termin do odstąpienia od Umowy sprzedaży lub złożenia oświadczenia o obniżeniu ceny rozpoczyna się z chwilą bezskutecznego upływu terminu do wymiany Towaru lub usunięcia wady.</span></li>
<li><span style="font-weight: 400;"> Wszelkie reklamacje związane z Towarem lub realizacją Umowy sprzedaży, Klient może kierować w formie pisemnej na adres Sprzedawcy.</span></li>
<li><span style="font-weight: 400;"> Sprzedawca w ciągu 14 dni od dnia żądania zawierającego reklamację, ustosunkuje się do reklamacji Towaru lub reklamacji związanej z realizacją Umowy sprzedaży zgłoszonej przez Klienta.</span></li>
<li><span style="font-weight: 400;"> Klient może zgłosić Sprzedawcy reklamację w związku z korzystaniem z usług nieodpłatnych świadczonych drogą elektroniczną przez Sprzedawcę. Reklamacja może być złożona w formie elektronicznej i przesłana na adres biuro@nextdesignsummit.pl. W zgłoszeniu reklamacyjnym Klient winien zawrzeć opis zaistniałego problemu. Sprzedawca niezwłocznie, lecz nie p&oacute;źniej niż w terminie 14 dni rozpatruje reklamacje i udziela Klientowi odpowiedzi.</span></li>
</ol>
<p>&nbsp;</p>
<p><strong>8 Odstąpienie od Umowy sprzedaży</strong></p>
<ol>
<li><span style="font-weight: 400;"> Klient będący Konsumentem, kt&oacute;ry zawarł Umowę sprzedaży, może w terminie 14 dni odstąpić od niej bez podawania przyczyny.</span></li>
<li><span style="font-weight: 400;"> Bieg terminu na odstąpienie od Umowy sprzedaży rozpoczyna się od chwili objęcia Towaru w posiadanie przez Klienta.</span></li>
</ol>
<p><span style="font-weight: 400;">&nbsp;Klient może odstąpić od Umowy sprzedaży składając Sprzedawcy oświadczenie o odstąpieniu. Oświadczenie można złożyć na formularzu, kt&oacute;rego wz&oacute;r został zamieszczony przez Sprzedawcę na Stronie Internetowej Sklepu pod adresem: Formularz odstąpienia. Do zachowania terminu wystarczy wysłanie oświadczenia przed jego upływem.</span></p>
<p><span style="font-weight: 400;">Klient może odstąpić od Umowy sprzedaży, składając Sprzedawcy oświadczenie o odstąpieniu za pośrednictwem formularza udostępnionego na stronie internetowej pod adresem: Elektroniczny Formularz odstąpienia. Do zachowania terminu wystarczy wysłanie oświadczenia przed jego upływem. Sprzedawca niezwłocznie potwierdza Klientowi otrzymanie formularza złożonego za pośrednictwem strony internetowej.</span></p>
<ol start="3">
<li><span style="font-weight: 400;"> W przypadku odstąpienia od Umowy sprzedaży, jest ona uważana za niezawartą.</span></li>
<li><span style="font-weight: 400;"> Jeśli Klient złożył oświadczenie o odstąpieniu od Umowy sprzedaży zanim Sprzedawca przyjął jego ofertę, oferta przestaje wiązać.</span></li>
<li><span style="font-weight: 400;"> Sprzedawca ma obowiązek niezwłocznie, nie p&oacute;źniej niż w terminie 14 dni od dnia otrzymania oświadczenia Klienta o odstąpieniu od Umowy sprzedaży, zwr&oacute;cić mu wszystkie dokonane przez niego płatności, w tym koszt Dostawy Towaru do Klienta. Sprzedawca może wstrzymać się ze zwrotem płatności otrzymanych od Klienta do chwili otrzymania z powrotem Towaru lub dostarczenia przez Klienta dowodu odesłania Towaru, w zależności od tego, kt&oacute;re zdarzenie nastąpi wcześniej.</span></li>
<li><span style="font-weight: 400;"> Jeżeli Klient korzystający z prawa do odstąpienia wybrał spos&oacute;b dostarczenia Towaru inny niż najtańszy zwykły spos&oacute;b Dostawy oferowany przez Sprzedawcę, Sprzedawca nie jest zobowiązany do zwrotu Klientowi poniesionych przez niego dodatkowych koszt&oacute;w.</span></li>
<li><span style="font-weight: 400;"> Klient ma obowiązek zwr&oacute;cić Towar Sprzedawcy niezwłocznie, jednak nie p&oacute;źniej niż w terminie 14 dni od dnia, w kt&oacute;rym odstąpił od Umowy sprzedaży. Do zachowania terminu wystarczy odesłanie Towaru na adres Sprzedawcy przed upływem tego terminu.</span></li>
<li><span style="font-weight: 400;"> W wypadku odstąpienia Klient ponosi tylko bezpośrednie koszty zwrotu Towaru.</span></li>
<li><span style="font-weight: 400;"> Jeśli ze względu na sw&oacute;j charakter Towar nie może zostać w zwykłym trybie odesłany pocztą, Sprzedawca informuje Klienta o kosztach zwrotu rzeczy na Stronie Internetowej Sklepu.</span></li>
<li><span style="font-weight: 400;"> Klient ponosi odpowiedzialność za zmniejszenie wartości Towaru będące wynikiem korzystania z niego w spos&oacute;b wykraczający poza spos&oacute;b konieczny do stwierdzenia charakteru, cech i funkcjonowania Towaru.</span></li>
<li><span style="font-weight: 400;"> Sprzedawca dokonuje zwrotu płatności przy użyciu takiego samego sposobu zapłaty, jakiego użył Klient, chyba, że Klient wyraźnie zgodził się na inny spos&oacute;b zwrotu, kt&oacute;ry nie wiąże się dla niego z żadnymi kosztami.</span></li>
<li><span style="font-weight: 400;"> Pozasądowe sposoby rozstrzygania spor&oacute;w:</span></li>
</ol>
<p><span style="font-weight: 400;">Informujemy, że Klientowi będącemu konsumentem przysługuje możliwość skorzystania z następujących, pozasądowych sposob&oacute;w rozpatrywania reklamacji oraz dochodzenia roszczeń:&nbsp;</span></p>
<ol>
<li><span style="font-weight: 400;">a) możliwość zwr&oacute;cenia się z wnioskiem o przeprowadzenie postępowania w sprawie pozasądowego rozwiązywania spor&oacute;w konsumenckich na podstawie Ustawy z dnia 23 września 2016 r. o pozasądowym rozwiązywaniu spor&oacute;w konsumenckich (Dz. U. z 2016 r., poz. 1823),</span></li>
<li><span style="font-weight: 400;">b) wystąpienie z wnioskiem o rozpoznanie sprawy przez Stały Polubowny Sąd Konsumencki działający przy odpowiednim Wojew&oacute;dzkim Inspektoracie Inspekcji Handlowej,</span></li>
<li><span style="font-weight: 400;">c) zwr&oacute;cenie się do Miejskiego Rzecznika Praw Konsument&oacute;w o pomoc w zakresie ochrony interes&oacute;w i praw konsument&oacute;w (np. http://konsument.um.warszawa.pl/). Bezpłatną pomoc konsumentom w zakresie ochrony ich praw i interes&oacute;w świadczą także organizacje społeczne, takie jak m.in. Federacja Konsument&oacute;w,</span></li>
</ol>
<p><span style="font-weight: 400;">&nbsp;Jeżeli dokonujesz zakupu Towar&oacute;w jako konsument, jesteś także uprawniony do skorzystania z pozasądowego sposobu rozpatrywania spor&oacute;w i dochodzenia roszczeń w postaci platformy interaktywnej ODR (Online Dispute Resolution), zgodnie z Rozporządzeniem Parlamentu Europejskiego i Rady (UE) Nr 524/2013 z dnia 21 maja 2013 r. w sprawie internetowego systemu rozstrzygania spor&oacute;w konsumenckich oraz zmiany Rozporządzenia (WE) nr 2006/2004 i dyrektywy 2009/WE, zwanym dalej &bdquo;ROZPORZĄDZENIEM W SPRAWIE ODR&rdquo;.</span></p>
<p><span style="font-weight: 400;">Stosownie do Art. 1 Rozporządzenia w sprawie ODR celem powstania platformy ODR jest udostępnienie konsumentom narzędzia ułatwiającego niezależne, bezstronne, przejrzyste, skuteczne, szybkie i sprawiedliwe pozasądowe rozstrzyganie przez internet spor&oacute;w między konsumentami i przedsiębiorcami na terytorium Unii Europejskiej.</span></p>
<p>&nbsp;</p>
<p><strong>9 Usługi nieodpłatne</strong></p>
<ol>
<li><span style="font-weight: 400;"> Sprzedawca świadczy na rzecz Klient&oacute;w, drogą elektroniczną usługi nieodpłatne:</span></li>
<li><span style="font-weight: 400;">a) Newsletter;</span></li>
<li><span style="font-weight: 400;">b) Prowadzenie Konta Klienta.</span></li>
<li><span style="font-weight: 400;"> Usługi wskazane w &sect;9 ust. 1 powyżej świadczone są 7 dni w tygodniu, 24 godziny na dobę.</span></li>
<li><span style="font-weight: 400;"> Sprzedawca zastrzega sobie możliwość wyboru i zmiany rodzaju, form, czasu oraz sposobu udzielania dostępu do wybranych wymienionych usług, o czym poinformuje Klient&oacute;w w spos&oacute;b właściwy dla zmiany Regulaminu.</span></li>
<li><span style="font-weight: 400;"> Z usługi Newsletter może skorzystać każdy Klient, kt&oacute;ry wprowadzi sw&oacute;j adres poczty elektronicznej, wykorzystując w tym celu formularz rejestracyjny udostępniony przez Sprzedawcę na Stronie Internetowej Sklepu. Po przesłaniu wypełnionego formularza rejestracyjnego, Klient otrzymuje niezwłocznie, drogą elektroniczną na adres poczty elektronicznej podany w formularzu rejestracyjnym potwierdzenie przez Sprzedawcę. Z tą chwilą zawarta zostaje umowa o świadczenie drogą elektroniczną usługi Newsletter.</span></li>
<li><span style="font-weight: 400;"> Usługa Newsletter polega na przesyłaniu przez Sprzedawcę, na adres poczty elektronicznej, wiadomości w formie elektronicznej zawierającej informacje o nowych produktach lub usługach w ofercie Sprzedawcy. Newsletter przesyłany jest przez Sprzedawcę do wszystkich Klient&oacute;w, kt&oacute;rzy dokonali subskrypcji.</span></li>
<li><span style="font-weight: 400;"> Każdy Newsletter kierowany do danych Klient&oacute;w zawiera, w szczeg&oacute;lności: informację o nadawcy, wypełnione pole &bdquo;temat&rdquo;, określające treść przesyłki oraz informację o możliwości i sposobie rezygnacji z usługi nieodpłatnej Newsletter.</span></li>
<li><span style="font-weight: 400;"> Klient może w każdej chwili zrezygnować z otrzymywania Newsletter&rsquo;a przez wypisanie się z subskrypcji za pośrednictwem odnośnika zamieszczonego w każdej wiadomości elektronicznej wysłanej w ramach usługi Newsletter lub za pośrednictwem aktywacji odpowiedniego pola w Koncie Klienta.</span></li>
<li><span style="font-weight: 400;"> Usługa Prowadzenie Konta Klienta dostępna jest po dokonaniu Rejestracji na zasadach opisanych w Regulaminie i polega na udostępnieniu Klientowi dedykowanego panelu w ramach Strony Internetowej Sklepu, umożliwiającego Klientowi modyfikacje danych, kt&oacute;re podał podczas Rejestracji, jak też śledzenia stanu realizacji zam&oacute;wień oraz historii zam&oacute;wień już zrealizowanych.</span></li>
<li><span style="font-weight: 400;"> Klient, kt&oacute;ry dokonał Rejestracji może zgłosić żądanie usunięcia Konta Klienta Sprzedawcy, przy czym w przypadku zgłoszenia żądania usunięcia Konta Klienta przez Sprzedawcę, może ono zostać usunięte do 14 dni od zgłoszenia żądania.</span></li>
<li><span style="font-weight: 400;"> Sprzedawca jest uprawniony do zablokowania dostępu do Konta Klienta i usług nieodpłatnych, w przypadku działania przez Klienta na szkodę Sprzedawcy lub innych Klient&oacute;w, naruszenia przez Klienta przepis&oacute;w prawa lub postanowień Regulaminu, a także, gdy zablokowanie dostępu do Konta Klienta i usług nieodpłatnych jest uzasadnione względami bezpieczeństwa - w szczeg&oacute;lności: przełamywaniem przez Klienta zabezpieczeń Strony Internetowej Sklepu lub innymi działaniami hakerskimi. Zablokowanie dostępu do Konta Klienta i usług nieodpłatnych z wymienionych przyczyn trwa przez okres niezbędny do rozwiązania kwestii stanowiącej podstawę zablokowania dostępu do Konta Klienta i usług nieodpłatnych. Sprzedawca zawiadamia Klienta o zablokowaniu dostępu do Konta Klienta i usług nieodpłatnych drogą elektroniczną na adres podany przez Klienta w formularzu rejestracyjnym.</span></li>
</ol>
<p>&nbsp;</p>
<p><strong>10 Ochrona danych osobowych</strong></p>
<ol>
<li><span style="font-weight: 400;"> Administratorem danych osobowych Klient&oacute;w przekazanych Sprzedawcy dobrowolnie w ramach Rejestracji, składania zam&oacute;wienia jednorazowego oraz w ramach świadczenia przez Sprzedawcę usług drogą elektroniczną lub w ramach innych okoliczności określonych w Regulaminie, jest Sprzedawca.</span></li>
<li><span style="font-weight: 400;"> Sprzedawca przetwarza dane osobowe Klient&oacute;w w celu realizacji zam&oacute;wień, świadczenia przez Sprzedawcę usług drogą elektroniczną oraz innych cel&oacute;w określonych w Regulaminie. Dane są przetwarzane wyłącznie na podstawie przepis&oacute;w prawa lub zgody wyrażonej przez Klienta zgodnie z obowiązującymi przepisami prawa.</span></li>
<li><span style="font-weight: 400;"> Zbi&oacute;r danych osobowych przekazanych Sprzedawcy zgłaszany jest przez Sprzedawcę Generalnemu Inspektorowi Ochrony Danych Osobowych.</span></li>
<li><span style="font-weight: 400;"> Klient przekazuje swoje dane osobowe Sprzedawcy dobrowolnie, z tym jednak zastrzeżeniem, że niepodanie określonych danych w procesie Rejestracji uniemożliwia Rejestrację i założenie Konta Klienta oraz uniemożliwia złożenie i realizację zam&oacute;wienia Klienta, w przypadku składania zam&oacute;wienia bez Rejestracji Konta Klienta.</span></li>
<li><span style="font-weight: 400;"> Każdy kto przekaże Sprzedawcy swoje dane osobowe, ma prawo dostępu do ich treści oraz do ich poprawiania.</span></li>
<li><span style="font-weight: 400;"> Sprzedawca zapewnia możliwość usunięcia danych osobowych z prowadzonego zbioru, w szczeg&oacute;lności w przypadku usunięcia Konta Klienta. Sprzedawca może odm&oacute;wić usunięcia danych osobowych, jeżeli Klient nie uregulował wszystkich należności wobec Sprzedawcy lub naruszył obowiązujące przepisy prawa, a zachowanie danych osobowych jest niezbędne do wyjaśnienia tych okoliczności i ustalenia odpowiedzialności Klienta.</span></li>
<li><span style="font-weight: 400;"> Sprzedawca chroni przekazane mu dane osobowe oraz dokłada wszelkich starań w celu zabezpieczenia ich przed nieuprawnionym dostępem lub wykorzystaniem.</span></li>
<li><span style="font-weight: 400;"> Sprzedawca przekazuje dane osobowe Klienta Dostawcy w zakresie niezbędnym do realizacji Dostawy.</span></li>
<li><span style="font-weight: 400;"> W przypadku, gdy Klient wybierze płatność poprzez system PayU, jego dane osobowe są przekazywane w zakresie niezbędnym dla realizacji płatności sp&oacute;łce PayU S.A. z siedzibą w Poznaniu (60-324 Poznań, ul. Grunwaldzka 182), wpisanej do rejestru przedsiębiorc&oacute;w prowadzonego przez Sąd Rejonowy Poznań - Nowe Miasto i Wilda w Poznaniu, Wydział VIII Gospodarczy Krajowego Rejestru Sądowego pod numerem KRS 0000274399.</span></li>
</ol>
<p>&nbsp;</p>
<p><strong>11 Postanowienia końcowe</strong></p>
<ol>
<li><span style="font-weight: 400;"> Sprzedawca ponosi odpowiedzialność z tytułu niewykonania lub nienależytego wykonania umowy, lecz w przypadku um&oacute;w zawieranych z Klientami będącymi Przedsiębiorcami Sprzedawca ponosi odpowiedzialność tylko w przypadku umyślnego wyrządzenia szkody i w granicach rzeczywiście poniesionych strat przez Klienta będącego Przedsiębiorcą.</span></li>
</ol>
<p><span style="font-weight: 400;">2.. Treść niniejszego Regulaminu może zostać utrwalona poprzez wydrukowanie, zapisanie na nośniku lub pobranie w każdej chwili ze Strony Internetowej Sklepu.</span></p>
<ol start="3">
<li><span style="font-weight: 400;"> W przypadku powstania sporu na gruncie zawartej Umowy sprzedaży, strony będą dążyły do rozwiązania sprawy polubownie. Prawem właściwym dla rozstrzygania wszelkich spor&oacute;w powstałych na gruncie niniejszego Regulaminu jest prawo polskie.</span></li>
<li><span style="font-weight: 400;"> Każdy Klient może skorzystać z pozasądowych sposob&oacute;w rozpatrywania reklamacji i dochodzenia roszczeń. W tym zakresie możliwe jest skorzystanie przez Klienta z mediacji. Listy stałych mediator&oacute;w oraz istniejących ośrodk&oacute;w mediacyjnych przekazywane są i udostępniane przez Prezes&oacute;w właściwych Sąd&oacute;w Okręgowych.</span></li>
<li><span style="font-weight: 400;"> Sprzedawca zastrzega sobie prawo zmiany niniejszego Regulaminu. Wszystkie zam&oacute;wienia przyjęte przez Sprzedawcę do realizacji przed dniem wejścia w życie nowego Regulaminu są realizowane na podstawie Regulaminu, kt&oacute;ry obowiązywał w dniu składania zam&oacute;wienia przez Klienta. Zmiana Regulaminu wchodzi w życie w terminie 7 dni od dnia opublikowania na Stronie Internetowej Sklepu. Sprzedawca poinformuje Klienta na 7 dni przed wejściem w życie nowego Regulaminu o zmianie Regulaminu za pomocą wiadomości przesłanej drogą elektroniczną zawierającej odnośnik do tekstu zmienionego Regulaminu. W razie, gdy Klient nie akceptuje nowej treści Regulaminu obowiązany jest zawiadomić o tym fakcie Sprzedawcę, co skutkuje rozwiązaniem umowy zgodnie z postanowieniami &sect;11 Regulaminu.</span></li>
<li><span style="font-weight: 400;"> Regulamin wchodzi w życie z dniem 01.09.2025 r.</span></li>
</ol>`;
